name: annotate_ranks

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  rank:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Set up dependencies
      run: |
        python -m pip install --upgrade pip
        pip install synapseclient challengeutils scipy

    - name: Annotate submission with ranks
      run: |
        python3 scripts/annotate_ranks.py
      env: 
        SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_PAT }}