name: rank_submissions

on:
  # schedule:
  #   - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  rank:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: r-lib/actions/setup-r@v2

      - name: Annotate submission with ranks
        run: |
          pip install synapseclient challengeutils 
          Rscript -e '
            options(repos = c(REPO_NAME = "https://packagemanager.rstudio.com/all/__linux__/bionic/latest", getOption("repos")));
            install.packages(c("dplyr", "reticulate", "data.table"))
          '
          Rscript scripts/rank_submissions.R
        env:
          SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_PAT }}
